name: Broken Link Check

on:
  schedule:
    - cron: '0 0 1 * *' # Run monthly on the 1st
  repository_dispatch:
    types: [check-links]
  push:
    branches:
      - main
    paths:
      - 'README.MD'
  pull_request:
    branches:
      - main
    paths:
      - 'README.MD'
  workflow_dispatch: # Allow manual trigger

jobs:
  check-links:
    name: Check Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './README.MD'
          fail: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue on Failure
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: ðŸ”— Broken Links Found
          content-filepath: ./lychee/out.md
          labels: documentation, maintenance

